name: Deploy App to Elastic Beanstalk

on:
  push:
    paths:
      - 'app/**'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:
      

jobs:

  sonar-scan:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: app

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  deploy:
    needs: sonar-scan
    runs-on: ubuntu-latest
    environment: app

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin \
          $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
        env:
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Docker Image
        run: docker build -t app ./app

      - name: Tag image
        run: |
          docker tag app:latest $ECR_REPO_URL:latest
          docker tag app:latest $ECR_REPO_URL:v-${{ github.run_number }}
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}

      
      - name: Push image to ECR
        run: |
          
          docker push $ECR_REPO_URL:v-${{ github.run_number }}
        env:
          ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}

      
      - name: Create Dockerrun file
        run: |
          cat <<EOF > Dockerrun.aws.json
          {
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "${{ secrets.ECR_REPO_URL }}:v-${{ github.run_number }}",
              "Update": "true"
            },
            "Ports": [
              { "ContainerPort": 80 }
            ]
          }
          EOF

      - name: Zip deployment
        run: zip deploy.zip Dockerrun.aws.json

      - name: Upload to S3
        run: |
          aws s3 cp deploy.zip s3://${{ secrets.S3_BUCKET }}/deploy.zip

      
      - name: Create EB version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APP_NAME }} \
            --version-label v-${{ github.run_number }} \
            --source-bundle S3Bucket=${{ secrets.S3_BUCKET }},S3Key=deploy.zip

      
      - name: Deploy to EB
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name ${{ secrets.EB_ENV_NAME }} \
            --version-label v-${{ github.run_number }}